// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cpu/cpu.proto

package cpu

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	basic "github.com/micro-in-cn/platform-web/assembly-line/protobuf/go/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProcStat struct {
	CPU                  string   `protobuf:"bytes,1,opt,name=CPU,json=cpu,proto3" json:"CPU,omitempty"`
	User                 float32  `protobuf:"fixed32,2,opt,name=user,proto3" json:"user,omitempty"`
	System               float32  `protobuf:"fixed32,3,opt,name=system,proto3" json:"system,omitempty"`
	Idle                 float32  `protobuf:"fixed32,4,opt,name=idle,proto3" json:"idle,omitempty"`
	Nice                 float32  `protobuf:"fixed32,5,opt,name=nice,proto3" json:"nice,omitempty"`
	Iowait               float32  `protobuf:"fixed32,6,opt,name=iowait,proto3" json:"iowait,omitempty"`
	Irq                  float32  `protobuf:"fixed32,7,opt,name=irq,proto3" json:"irq,omitempty"`
	Softirq              float32  `protobuf:"fixed32,8,opt,name=softirq,proto3" json:"softirq,omitempty"`
	Steal                float32  `protobuf:"fixed32,9,opt,name=steal,proto3" json:"steal,omitempty"`
	Guest                float32  `protobuf:"fixed32,10,opt,name=guest,proto3" json:"guest,omitempty"`
	GuestNice            float32  `protobuf:"fixed32,11,opt,name=guestNice,proto3" json:"guestNice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcStat) Reset()         { *m = ProcStat{} }
func (m *ProcStat) String() string { return proto.CompactTextString(m) }
func (*ProcStat) ProtoMessage()    {}
func (*ProcStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_01f0493b3e98ba1a, []int{0}
}

func (m *ProcStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcStat.Unmarshal(m, b)
}
func (m *ProcStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcStat.Marshal(b, m, deterministic)
}
func (m *ProcStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcStat.Merge(m, src)
}
func (m *ProcStat) XXX_Size() int {
	return xxx_messageInfo_ProcStat.Size(m)
}
func (m *ProcStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcStat.DiscardUnknown(m)
}

var xxx_messageInfo_ProcStat proto.InternalMessageInfo

func (m *ProcStat) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *ProcStat) GetUser() float32 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *ProcStat) GetSystem() float32 {
	if m != nil {
		return m.System
	}
	return 0
}

func (m *ProcStat) GetIdle() float32 {
	if m != nil {
		return m.Idle
	}
	return 0
}

func (m *ProcStat) GetNice() float32 {
	if m != nil {
		return m.Nice
	}
	return 0
}

func (m *ProcStat) GetIowait() float32 {
	if m != nil {
		return m.Iowait
	}
	return 0
}

func (m *ProcStat) GetIrq() float32 {
	if m != nil {
		return m.Irq
	}
	return 0
}

func (m *ProcStat) GetSoftirq() float32 {
	if m != nil {
		return m.Softirq
	}
	return 0
}

func (m *ProcStat) GetSteal() float32 {
	if m != nil {
		return m.Steal
	}
	return 0
}

func (m *ProcStat) GetGuest() float32 {
	if m != nil {
		return m.Guest
	}
	return 0
}

func (m *ProcStat) GetGuestNice() float32 {
	if m != nil {
		return m.GuestNice
	}
	return 0
}

type CPURequest struct {
	IP                   string    `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	NodeName             string    `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	ProcStat             *ProcStat `protobuf:"bytes,3,opt,name=procStat,proto3" json:"procStat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CPURequest) Reset()         { *m = CPURequest{} }
func (m *CPURequest) String() string { return proto.CompactTextString(m) }
func (*CPURequest) ProtoMessage()    {}
func (*CPURequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_01f0493b3e98ba1a, []int{1}
}

func (m *CPURequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPURequest.Unmarshal(m, b)
}
func (m *CPURequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPURequest.Marshal(b, m, deterministic)
}
func (m *CPURequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPURequest.Merge(m, src)
}
func (m *CPURequest) XXX_Size() int {
	return xxx_messageInfo_CPURequest.Size(m)
}
func (m *CPURequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CPURequest.DiscardUnknown(m)
}

var xxx_messageInfo_CPURequest proto.InternalMessageInfo

func (m *CPURequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *CPURequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *CPURequest) GetProcStat() *ProcStat {
	if m != nil {
		return m.ProcStat
	}
	return nil
}

type CPUResponse struct {
	Error                *basic.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CPUResponse) Reset()         { *m = CPUResponse{} }
func (m *CPUResponse) String() string { return proto.CompactTextString(m) }
func (*CPUResponse) ProtoMessage()    {}
func (*CPUResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_01f0493b3e98ba1a, []int{2}
}

func (m *CPUResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPUResponse.Unmarshal(m, b)
}
func (m *CPUResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPUResponse.Marshal(b, m, deterministic)
}
func (m *CPUResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUResponse.Merge(m, src)
}
func (m *CPUResponse) XXX_Size() int {
	return xxx_messageInfo_CPUResponse.Size(m)
}
func (m *CPUResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CPUResponse proto.InternalMessageInfo

func (m *CPUResponse) GetError() *basic.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*ProcStat)(nil), "protobuf.pb.cpu.cpu.ProcStat")
	proto.RegisterType((*CPURequest)(nil), "protobuf.pb.cpu.cpu.CPURequest")
	proto.RegisterType((*CPUResponse)(nil), "protobuf.pb.cpu.cpu.CPUResponse")
}

func init() { proto.RegisterFile("cpu/cpu.proto", fileDescriptor_01f0493b3e98ba1a) }

var fileDescriptor_01f0493b3e98ba1a = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcb, 0x8b, 0xdb, 0x30,
	0x10, 0xc6, 0x9b, 0x64, 0x93, 0x8d, 0xc7, 0xf4, 0xa5, 0x3e, 0x10, 0xa1, 0xa5, 0xc1, 0xa7, 0x85,
	0x62, 0x0b, 0xd2, 0x53, 0x7b, 0x6c, 0x58, 0xca, 0x5e, 0x16, 0xe3, 0x25, 0x3d, 0xf4, 0x66, 0x2b,
	0x4a, 0x56, 0x60, 0x5b, 0x5a, 0x3d, 0xba, 0xec, 0x3f, 0x5f, 0x8a, 0x46, 0x4e, 0x72, 0xc9, 0x9e,
	0x32, 0xdf, 0x4f, 0x9f, 0x34, 0x93, 0x6f, 0x0c, 0x2f, 0xb9, 0xf6, 0x8c, 0x6b, 0x5f, 0x68, 0xa3,
	0x9c, 0x22, 0xef, 0xf0, 0xa7, 0xf1, 0xbb, 0x42, 0x37, 0x45, 0xc0, 0x5c, 0xfb, 0xc5, 0xdb, 0xa6,
	0xb6, 0x92, 0x33, 0x61, 0x8c, 0x32, 0xd1, 0x97, 0xfd, 0x1b, 0xc1, 0xbc, 0x34, 0x8a, 0xdf, 0xb9,
	0xda, 0x91, 0x37, 0x30, 0x59, 0x97, 0x1b, 0x3a, 0x5a, 0x8e, 0xae, 0x92, 0x6a, 0xc2, 0xb5, 0x27,
	0x04, 0x2e, 0xbc, 0x15, 0x86, 0x8e, 0x97, 0xa3, 0xab, 0x71, 0x85, 0x35, 0xf9, 0x08, 0x33, 0xfb,
	0x64, 0x9d, 0xe8, 0xe8, 0x04, 0xe9, 0xa0, 0x82, 0x57, 0x6e, 0x5b, 0x41, 0x2f, 0xa2, 0x37, 0xd4,
	0x81, 0xf5, 0x92, 0x0b, 0x3a, 0x8d, 0x2c, 0xd4, 0xe1, 0xbe, 0x54, 0x8f, 0xb5, 0x74, 0x74, 0x16,
	0xef, 0x47, 0x15, 0xba, 0x4b, 0xf3, 0x40, 0x2f, 0x11, 0x86, 0x92, 0x50, 0xb8, 0xb4, 0x6a, 0xe7,
	0x02, 0x9d, 0x23, 0x3d, 0x48, 0xf2, 0x1e, 0xa6, 0xd6, 0x89, 0xba, 0xa5, 0x09, 0xf2, 0x28, 0x02,
	0xdd, 0x7b, 0x61, 0x1d, 0x85, 0x48, 0x51, 0x90, 0x4f, 0x90, 0x60, 0x71, 0x1b, 0x06, 0x49, 0xf1,
	0xe4, 0x04, 0x32, 0x0b, 0xb0, 0x2e, 0x37, 0x95, 0x78, 0x40, 0xef, 0x2b, 0x18, 0xdf, 0x94, 0x43,
	0x00, 0xe3, 0x9b, 0x92, 0x2c, 0x60, 0xde, 0xab, 0xad, 0xb8, 0xad, 0x3b, 0x81, 0x19, 0x24, 0xd5,
	0x51, 0x93, 0xef, 0x30, 0xd7, 0x43, 0x72, 0x98, 0x44, 0xba, 0xfa, 0x5c, 0x9c, 0x49, 0xbd, 0x38,
	0xc4, 0x5b, 0x1d, 0xed, 0xd9, 0x0f, 0x48, 0xb1, 0xa9, 0xd5, 0xaa, 0xb7, 0x82, 0x7c, 0x85, 0x29,
	0xee, 0x04, 0x1b, 0xa7, 0xab, 0x0f, 0xa7, 0x67, 0x70, 0x61, 0xc5, 0x75, 0x38, 0xac, 0xa2, 0x67,
	0xb5, 0xc5, 0x81, 0xef, 0x84, 0xf9, 0x1b, 0xc2, 0xfc, 0x0d, 0xaf, 0x4b, 0x6f, 0xef, 0xd7, 0xe5,
	0xe6, 0xb8, 0xc5, 0x2f, 0x67, 0xa7, 0x38, 0xfd, 0xc9, 0xc5, 0xf2, 0x79, 0x43, 0x1c, 0x28, 0x7b,
	0xf1, 0xf3, 0xd7, 0x9f, 0xeb, 0xbd, 0x74, 0xf7, 0xbe, 0x29, 0xb8, 0xea, 0x58, 0x27, 0xb9, 0x51,
	0xb9, 0xec, 0x73, 0xde, 0x33, 0xdd, 0xd6, 0x6e, 0xa7, 0x4c, 0x97, 0x3f, 0x8a, 0x86, 0xd5, 0xd6,
	0x8a, 0xae, 0x69, 0x9f, 0xf2, 0x56, 0xf6, 0x82, 0x1d, 0x9e, 0x65, 0x7b, 0xc5, 0x86, 0xcf, 0xb1,
	0x99, 0x21, 0xfc, 0xf6, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xf2, 0xcb, 0x97, 0xa0, 0x02, 0x00,
	0x00,
}
