// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mem/mem.proto

package mem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	basic "github.com/micro-in-cn/platform-web/assembly-line/protobuf/go/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MemoryStat struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveBytes          float64              `protobuf:"fixed64,2,opt,name=ActiveBytes,proto3" json:"ActiveBytes,omitempty"`
	CompressedBytes      float64              `protobuf:"fixed64,3,opt,name=CompressedBytes,proto3" json:"CompressedBytes,omitempty"`
	InactiveBytes        float64              `protobuf:"fixed64,4,opt,name=InactiveBytes,proto3" json:"InactiveBytes,omitempty"`
	WiredBytes           float64              `protobuf:"fixed64,5,opt,name=WiredBytes,proto3" json:"WiredBytes,omitempty"`
	FreeBytes            float64              `protobuf:"fixed64,6,opt,name=FreeBytes,proto3" json:"FreeBytes,omitempty"`
	SwappedInBytesTotal  float64              `protobuf:"fixed64,7,opt,name=SwappedInBytesTotal,proto3" json:"SwappedInBytesTotal,omitempty"`
	SwappedOutBytesTotal float64              `protobuf:"fixed64,8,opt,name=SwappedOutBytesTotal,proto3" json:"SwappedOutBytesTotal,omitempty"`
	TotalBytes           float64              `protobuf:"fixed64,9,opt,name=TotalBytes,proto3" json:"TotalBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MemoryStat) Reset()         { *m = MemoryStat{} }
func (m *MemoryStat) String() string { return proto.CompactTextString(m) }
func (*MemoryStat) ProtoMessage()    {}
func (*MemoryStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2907961eca7e66, []int{0}
}

func (m *MemoryStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryStat.Unmarshal(m, b)
}
func (m *MemoryStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryStat.Marshal(b, m, deterministic)
}
func (m *MemoryStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryStat.Merge(m, src)
}
func (m *MemoryStat) XXX_Size() int {
	return xxx_messageInfo_MemoryStat.Size(m)
}
func (m *MemoryStat) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryStat.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryStat proto.InternalMessageInfo

func (m *MemoryStat) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *MemoryStat) GetActiveBytes() float64 {
	if m != nil {
		return m.ActiveBytes
	}
	return 0
}

func (m *MemoryStat) GetCompressedBytes() float64 {
	if m != nil {
		return m.CompressedBytes
	}
	return 0
}

func (m *MemoryStat) GetInactiveBytes() float64 {
	if m != nil {
		return m.InactiveBytes
	}
	return 0
}

func (m *MemoryStat) GetWiredBytes() float64 {
	if m != nil {
		return m.WiredBytes
	}
	return 0
}

func (m *MemoryStat) GetFreeBytes() float64 {
	if m != nil {
		return m.FreeBytes
	}
	return 0
}

func (m *MemoryStat) GetSwappedInBytesTotal() float64 {
	if m != nil {
		return m.SwappedInBytesTotal
	}
	return 0
}

func (m *MemoryStat) GetSwappedOutBytesTotal() float64 {
	if m != nil {
		return m.SwappedOutBytesTotal
	}
	return 0
}

func (m *MemoryStat) GetTotalBytes() float64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

type MemRequest struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IP                   string               `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	NodeName             string               `protobuf:"bytes,3,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	MemoryStat           []*MemoryStat        `protobuf:"bytes,4,rep,name=MemoryStat,proto3" json:"MemoryStat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MemRequest) Reset()         { *m = MemRequest{} }
func (m *MemRequest) String() string { return proto.CompactTextString(m) }
func (*MemRequest) ProtoMessage()    {}
func (*MemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2907961eca7e66, []int{1}
}

func (m *MemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemRequest.Unmarshal(m, b)
}
func (m *MemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemRequest.Marshal(b, m, deterministic)
}
func (m *MemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemRequest.Merge(m, src)
}
func (m *MemRequest) XXX_Size() int {
	return xxx_messageInfo_MemRequest.Size(m)
}
func (m *MemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemRequest proto.InternalMessageInfo

func (m *MemRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *MemRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *MemRequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *MemRequest) GetMemoryStat() []*MemoryStat {
	if m != nil {
		return m.MemoryStat
	}
	return nil
}

type MemResponse struct {
	Error                *basic.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MemResponse) Reset()         { *m = MemResponse{} }
func (m *MemResponse) String() string { return proto.CompactTextString(m) }
func (*MemResponse) ProtoMessage()    {}
func (*MemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2907961eca7e66, []int{2}
}

func (m *MemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemResponse.Unmarshal(m, b)
}
func (m *MemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemResponse.Marshal(b, m, deterministic)
}
func (m *MemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemResponse.Merge(m, src)
}
func (m *MemResponse) XXX_Size() int {
	return xxx_messageInfo_MemResponse.Size(m)
}
func (m *MemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemResponse proto.InternalMessageInfo

func (m *MemResponse) GetError() *basic.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*MemoryStat)(nil), "protobuf.pb.mem.MemoryStat")
	proto.RegisterType((*MemRequest)(nil), "protobuf.pb.mem.MemRequest")
	proto.RegisterType((*MemResponse)(nil), "protobuf.pb.mem.MemResponse")
}

func init() { proto.RegisterFile("mem/mem.proto", fileDescriptor_6d2907961eca7e66) }

var fileDescriptor_6d2907961eca7e66 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x71, 0xfa, 0x87, 0x7a, 0xa2, 0xb6, 0x62, 0x01, 0x29, 0x32, 0x15, 0x44, 0x11, 0x87,
	0x48, 0x28, 0x6b, 0x14, 0x2e, 0x08, 0x4e, 0x14, 0x15, 0x94, 0x43, 0x21, 0x72, 0x2a, 0x21, 0xc1,
	0x69, 0xed, 0x4c, 0xd3, 0x95, 0xbc, 0x5e, 0xb3, 0xbb, 0x6e, 0x95, 0x4f, 0xc5, 0x17, 0xe4, 0x80,
	0x3a, 0x76, 0xe2, 0x25, 0xf2, 0xad, 0x27, 0xdb, 0x6f, 0x7e, 0x3b, 0xfb, 0xf4, 0x3c, 0x03, 0xc7,
	0x0a, 0x55, 0xac, 0x50, 0xf1, 0xd2, 0x68, 0xa7, 0xd9, 0x29, 0x3d, 0xd2, 0xea, 0x9a, 0x97, 0x29,
	0x57, 0xa8, 0xa2, 0x27, 0xa9, 0xb0, 0x32, 0x8b, 0xd1, 0x18, 0x6d, 0x6a, 0x26, 0x7a, 0xb5, 0xd2,
	0x7a, 0x95, 0x63, 0xbc, 0x41, 0x63, 0x27, 0x15, 0x5a, 0x27, 0x54, 0x59, 0x03, 0xa3, 0xbf, 0x3d,
	0x80, 0x4b, 0x54, 0xda, 0xac, 0x17, 0x4e, 0x38, 0xf6, 0x1e, 0xc2, 0x2d, 0x31, 0x08, 0x86, 0xc1,
	0xb8, 0x3f, 0x8d, 0x78, 0xdd, 0x83, 0x6f, 0xaf, 0xbb, 0xda, 0x10, 0x49, 0x0b, 0xb3, 0x21, 0xf4,
	0x3f, 0x65, 0x4e, 0xde, 0xe2, 0xf9, 0xda, 0xa1, 0x1d, 0xf4, 0x86, 0xc1, 0x38, 0x48, 0x7c, 0x89,
	0x8d, 0xe1, 0xf4, 0xb3, 0x56, 0xa5, 0x41, 0x6b, 0x71, 0x59, 0x53, 0x7b, 0x44, 0xed, 0xca, 0xec,
	0x35, 0x1c, 0xcf, 0x0a, 0xe1, 0x75, 0xdb, 0x27, 0xee, 0x7f, 0x91, 0xbd, 0x04, 0xf8, 0x21, 0xcd,
	0xa6, 0xd5, 0x01, 0x21, 0x9e, 0xc2, 0xce, 0x20, 0xfc, 0x62, 0xb0, 0xe9, 0x70, 0x48, 0xe5, 0x56,
	0x60, 0x6f, 0xe1, 0xe9, 0xe2, 0x4e, 0x94, 0x25, 0x2e, 0x67, 0x05, 0x29, 0x57, 0xda, 0x89, 0x7c,
	0xf0, 0x98, 0xb8, 0xae, 0x12, 0x9b, 0xc2, 0xb3, 0x46, 0xfe, 0x5e, 0x39, 0xef, 0xc8, 0x11, 0x1d,
	0xe9, 0xac, 0xdd, 0x7b, 0xa4, 0x97, 0xda, 0x44, 0x58, 0x7b, 0x6c, 0x95, 0xd1, 0x9f, 0x80, 0xe2,
	0x4f, 0xf0, 0x77, 0x85, 0xf6, 0x21, 0xf1, 0x9f, 0x40, 0x6f, 0x36, 0xa7, 0xd4, 0xc3, 0xa4, 0x37,
	0x9b, 0xb3, 0x08, 0x8e, 0x0a, 0xbd, 0xc4, 0x6f, 0x42, 0x21, 0xa5, 0x1c, 0x26, 0xdb, 0x6f, 0xf6,
	0xd1, 0xff, 0xe5, 0x83, 0xfd, 0xe1, 0xde, 0xb8, 0x3f, 0x7d, 0xc1, 0x77, 0xa6, 0x89, 0xb7, 0x48,
	0xe2, 0xe1, 0xa3, 0x0f, 0xd0, 0x27, 0xc3, 0xb6, 0xd4, 0x85, 0x45, 0xf6, 0x06, 0x0e, 0x68, 0xde,
	0x1a, 0xb7, 0xcf, 0xdb, 0x36, 0x34, 0x8c, 0xfc, 0xe2, 0xbe, 0x98, 0xd4, 0xcc, 0xf4, 0x17, 0x5d,
	0xbc, 0x40, 0x73, 0x2b, 0x33, 0x64, 0x97, 0x70, 0x32, 0xaf, 0xec, 0x8d, 0x37, 0x7d, 0x9d, 0x26,
	0x9a, 0x6c, 0xa2, 0xb3, 0xee, 0x62, 0xed, 0x63, 0xf4, 0xe8, 0xfc, 0xeb, 0xcf, 0x8b, 0x95, 0x74,
	0x37, 0x55, 0xca, 0x33, 0xad, 0x62, 0x25, 0x33, 0xa3, 0x27, 0xb2, 0x98, 0x64, 0x45, 0x5c, 0xe6,
	0xc2, 0x5d, 0x6b, 0xa3, 0x26, 0x77, 0x98, 0xc6, 0xc2, 0x5a, 0x54, 0x69, 0xbe, 0x9e, 0xe4, 0xb2,
	0xf0, 0xf6, 0x62, 0xa5, 0xe3, 0x66, 0xbb, 0xd2, 0x43, 0x12, 0xdf, 0xfd, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0x9f, 0xe8, 0xde, 0x6f, 0x03, 0x00, 0x00,
}
