// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: mem/mem.proto

package mem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/micro-in-cn/platform-web/assembly-line/protobuf/go/basic"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DiskService service

type DiskService interface {
	PushVirtualMemoryStat(ctx context.Context, in *MemRequest, opts ...client.CallOption) (*MemResponse, error)
	PushSwapMemoryStat(ctx context.Context, in *MemRequest, opts ...client.CallOption) (*MemResponse, error)
}

type diskService struct {
	c    client.Client
	name string
}

func NewDiskService(name string, c client.Client) DiskService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "protobuf.pb.mem"
	}
	return &diskService{
		c:    c,
		name: name,
	}
}

func (c *diskService) PushVirtualMemoryStat(ctx context.Context, in *MemRequest, opts ...client.CallOption) (*MemResponse, error) {
	req := c.c.NewRequest(c.name, "DiskService.PushVirtualMemoryStat", in)
	out := new(MemResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskService) PushSwapMemoryStat(ctx context.Context, in *MemRequest, opts ...client.CallOption) (*MemResponse, error) {
	req := c.c.NewRequest(c.name, "DiskService.PushSwapMemoryStat", in)
	out := new(MemResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiskService service

type DiskServiceHandler interface {
	PushVirtualMemoryStat(context.Context, *MemRequest, *MemResponse) error
	PushSwapMemoryStat(context.Context, *MemRequest, *MemResponse) error
}

func RegisterDiskServiceHandler(s server.Server, hdlr DiskServiceHandler, opts ...server.HandlerOption) error {
	type diskService interface {
		PushVirtualMemoryStat(ctx context.Context, in *MemRequest, out *MemResponse) error
		PushSwapMemoryStat(ctx context.Context, in *MemRequest, out *MemResponse) error
	}
	type DiskService struct {
		diskService
	}
	h := &diskServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DiskService{h}, opts...))
}

type diskServiceHandler struct {
	DiskServiceHandler
}

func (h *diskServiceHandler) PushVirtualMemoryStat(ctx context.Context, in *MemRequest, out *MemResponse) error {
	return h.DiskServiceHandler.PushVirtualMemoryStat(ctx, in, out)
}

func (h *diskServiceHandler) PushSwapMemoryStat(ctx context.Context, in *MemRequest, out *MemResponse) error {
	return h.DiskServiceHandler.PushSwapMemoryStat(ctx, in, out)
}
