// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: mem/mem.proto

package mem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/micro-in-cn/platform-web/assembly-line/protobuf/go/basic"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MemService service

type MemService interface {
	PushMemoryStat(ctx context.Context, in *MemRequest, opts ...client.CallOption) (*MemResponse, error)
}

type memService struct {
	c    client.Client
	name string
}

func NewMemService(name string, c client.Client) MemService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "protobuf.pb.mem"
	}
	return &memService{
		c:    c,
		name: name,
	}
}

func (c *memService) PushMemoryStat(ctx context.Context, in *MemRequest, opts ...client.CallOption) (*MemResponse, error) {
	req := c.c.NewRequest(c.name, "MemService.PushMemoryStat", in)
	out := new(MemResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemService service

type MemServiceHandler interface {
	PushMemoryStat(context.Context, *MemRequest, *MemResponse) error
}

func RegisterMemServiceHandler(s server.Server, hdlr MemServiceHandler, opts ...server.HandlerOption) error {
	type memService interface {
		PushMemoryStat(ctx context.Context, in *MemRequest, out *MemResponse) error
	}
	type MemService struct {
		memService
	}
	h := &memServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MemService{h}, opts...))
}

type memServiceHandler struct {
	MemServiceHandler
}

func (h *memServiceHandler) PushMemoryStat(ctx context.Context, in *MemRequest, out *MemResponse) error {
	return h.MemServiceHandler.PushMemoryStat(ctx, in, out)
}
