// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: disk/disk.proto

package disk

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/micro-in-cn/platform-web/assembly-line/protobuf/go/basic"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DiskService service

type DiskService interface {
	PushDiskUsageStat(ctx context.Context, in *DiskRequest, opts ...client.CallOption) (*DiskResponse, error)
	PushPartitionStat(ctx context.Context, in *DiskRequest, opts ...client.CallOption) (*DiskResponse, error)
	PushIOCountersStat(ctx context.Context, in *DiskRequest, opts ...client.CallOption) (*DiskResponse, error)
}

type diskService struct {
	c    client.Client
	name string
}

func NewDiskService(name string, c client.Client) DiskService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "protobuf.pb.cpu.cpu"
	}
	return &diskService{
		c:    c,
		name: name,
	}
}

func (c *diskService) PushDiskUsageStat(ctx context.Context, in *DiskRequest, opts ...client.CallOption) (*DiskResponse, error) {
	req := c.c.NewRequest(c.name, "DiskService.PushDiskUsageStat", in)
	out := new(DiskResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskService) PushPartitionStat(ctx context.Context, in *DiskRequest, opts ...client.CallOption) (*DiskResponse, error) {
	req := c.c.NewRequest(c.name, "DiskService.PushPartitionStat", in)
	out := new(DiskResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskService) PushIOCountersStat(ctx context.Context, in *DiskRequest, opts ...client.CallOption) (*DiskResponse, error) {
	req := c.c.NewRequest(c.name, "DiskService.PushIOCountersStat", in)
	out := new(DiskResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiskService service

type DiskServiceHandler interface {
	PushDiskUsageStat(context.Context, *DiskRequest, *DiskResponse) error
	PushPartitionStat(context.Context, *DiskRequest, *DiskResponse) error
	PushIOCountersStat(context.Context, *DiskRequest, *DiskResponse) error
}

func RegisterDiskServiceHandler(s server.Server, hdlr DiskServiceHandler, opts ...server.HandlerOption) error {
	type diskService interface {
		PushDiskUsageStat(ctx context.Context, in *DiskRequest, out *DiskResponse) error
		PushPartitionStat(ctx context.Context, in *DiskRequest, out *DiskResponse) error
		PushIOCountersStat(ctx context.Context, in *DiskRequest, out *DiskResponse) error
	}
	type DiskService struct {
		diskService
	}
	h := &diskServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DiskService{h}, opts...))
}

type diskServiceHandler struct {
	DiskServiceHandler
}

func (h *diskServiceHandler) PushDiskUsageStat(ctx context.Context, in *DiskRequest, out *DiskResponse) error {
	return h.DiskServiceHandler.PushDiskUsageStat(ctx, in, out)
}

func (h *diskServiceHandler) PushPartitionStat(ctx context.Context, in *DiskRequest, out *DiskResponse) error {
	return h.DiskServiceHandler.PushPartitionStat(ctx, in, out)
}

func (h *diskServiceHandler) PushIOCountersStat(ctx context.Context, in *DiskRequest, out *DiskResponse) error {
	return h.DiskServiceHandler.PushIOCountersStat(ctx, in, out)
}
