// Code generated by protoc-gen-go. DO NOT EDIT.
// source: disk/disk.proto

package disk

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	basic "github.com/micro-in-cn/platform-web/assembly-line/protobuf/go/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsageStat struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Path                 string               `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Fstype               string               `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Total                uint64               `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Free                 uint64               `protobuf:"varint,5,opt,name=free,proto3" json:"free,omitempty"`
	Used                 uint64               `protobuf:"varint,6,opt,name=used,proto3" json:"used,omitempty"`
	UsedPercent          float64              `protobuf:"fixed64,7,opt,name=usedPercent,proto3" json:"usedPercent,omitempty"`
	InodesTotal          uint64               `protobuf:"varint,8,opt,name=inodesTotal,proto3" json:"inodesTotal,omitempty"`
	InodesUsed           uint64               `protobuf:"varint,9,opt,name=inodesUsed,proto3" json:"inodesUsed,omitempty"`
	InodesFree           uint64               `protobuf:"varint,10,opt,name=inodesFree,proto3" json:"inodesFree,omitempty"`
	InodesUsedPercent    float64              `protobuf:"fixed64,11,opt,name=inodesUsedPercent,proto3" json:"inodesUsedPercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UsageStat) Reset()         { *m = UsageStat{} }
func (m *UsageStat) String() string { return proto.CompactTextString(m) }
func (*UsageStat) ProtoMessage()    {}
func (*UsageStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_87be47849fd92a15, []int{0}
}

func (m *UsageStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsageStat.Unmarshal(m, b)
}
func (m *UsageStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsageStat.Marshal(b, m, deterministic)
}
func (m *UsageStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsageStat.Merge(m, src)
}
func (m *UsageStat) XXX_Size() int {
	return xxx_messageInfo_UsageStat.Size(m)
}
func (m *UsageStat) XXX_DiscardUnknown() {
	xxx_messageInfo_UsageStat.DiscardUnknown(m)
}

var xxx_messageInfo_UsageStat proto.InternalMessageInfo

func (m *UsageStat) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *UsageStat) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *UsageStat) GetFstype() string {
	if m != nil {
		return m.Fstype
	}
	return ""
}

func (m *UsageStat) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UsageStat) GetFree() uint64 {
	if m != nil {
		return m.Free
	}
	return 0
}

func (m *UsageStat) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *UsageStat) GetUsedPercent() float64 {
	if m != nil {
		return m.UsedPercent
	}
	return 0
}

func (m *UsageStat) GetInodesTotal() uint64 {
	if m != nil {
		return m.InodesTotal
	}
	return 0
}

func (m *UsageStat) GetInodesUsed() uint64 {
	if m != nil {
		return m.InodesUsed
	}
	return 0
}

func (m *UsageStat) GetInodesFree() uint64 {
	if m != nil {
		return m.InodesFree
	}
	return 0
}

func (m *UsageStat) GetInodesUsedPercent() float64 {
	if m != nil {
		return m.InodesUsedPercent
	}
	return 0
}

type PartitionStat struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Device               string               `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Mountpoint           string               `protobuf:"bytes,3,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Fstype               string               `protobuf:"bytes,4,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Opts                 string               `protobuf:"bytes,5,opt,name=opts,proto3" json:"opts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PartitionStat) Reset()         { *m = PartitionStat{} }
func (m *PartitionStat) String() string { return proto.CompactTextString(m) }
func (*PartitionStat) ProtoMessage()    {}
func (*PartitionStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_87be47849fd92a15, []int{1}
}

func (m *PartitionStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionStat.Unmarshal(m, b)
}
func (m *PartitionStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionStat.Marshal(b, m, deterministic)
}
func (m *PartitionStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionStat.Merge(m, src)
}
func (m *PartitionStat) XXX_Size() int {
	return xxx_messageInfo_PartitionStat.Size(m)
}
func (m *PartitionStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionStat.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionStat proto.InternalMessageInfo

func (m *PartitionStat) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *PartitionStat) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *PartitionStat) GetMountpoint() string {
	if m != nil {
		return m.Mountpoint
	}
	return ""
}

func (m *PartitionStat) GetFstype() string {
	if m != nil {
		return m.Fstype
	}
	return ""
}

func (m *PartitionStat) GetOpts() string {
	if m != nil {
		return m.Opts
	}
	return ""
}

type IOCountersStat struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReadCount            uint64               `protobuf:"varint,2,opt,name=readCount,proto3" json:"readCount,omitempty"`
	MergedReadCount      uint64               `protobuf:"varint,3,opt,name=mergedReadCount,proto3" json:"mergedReadCount,omitempty"`
	WriteCount           uint64               `protobuf:"varint,4,opt,name=writeCount,proto3" json:"writeCount,omitempty"`
	MergedWriteCount     uint64               `protobuf:"varint,5,opt,name=mergedWriteCount,proto3" json:"mergedWriteCount,omitempty"`
	ReadBytes            uint64               `protobuf:"varint,6,opt,name=readBytes,proto3" json:"readBytes,omitempty"`
	WriteBytes           uint64               `protobuf:"varint,7,opt,name=writeBytes,proto3" json:"writeBytes,omitempty"`
	ReadTime             uint64               `protobuf:"varint,8,opt,name=readTime,proto3" json:"readTime,omitempty"`
	WriteTime            uint64               `protobuf:"varint,9,opt,name=writeTime,proto3" json:"writeTime,omitempty"`
	IopsInProgress       uint64               `protobuf:"varint,10,opt,name=iopsInProgress,proto3" json:"iopsInProgress,omitempty"`
	IoTime               uint64               `protobuf:"varint,11,opt,name=ioTime,proto3" json:"ioTime,omitempty"`
	WeightedIO           uint64               `protobuf:"varint,12,opt,name=weightedIO,proto3" json:"weightedIO,omitempty"`
	Name                 string               `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	SerialNumber         string               `protobuf:"bytes,14,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	Label                string               `protobuf:"bytes,15,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IOCountersStat) Reset()         { *m = IOCountersStat{} }
func (m *IOCountersStat) String() string { return proto.CompactTextString(m) }
func (*IOCountersStat) ProtoMessage()    {}
func (*IOCountersStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_87be47849fd92a15, []int{2}
}

func (m *IOCountersStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IOCountersStat.Unmarshal(m, b)
}
func (m *IOCountersStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IOCountersStat.Marshal(b, m, deterministic)
}
func (m *IOCountersStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOCountersStat.Merge(m, src)
}
func (m *IOCountersStat) XXX_Size() int {
	return xxx_messageInfo_IOCountersStat.Size(m)
}
func (m *IOCountersStat) XXX_DiscardUnknown() {
	xxx_messageInfo_IOCountersStat.DiscardUnknown(m)
}

var xxx_messageInfo_IOCountersStat proto.InternalMessageInfo

func (m *IOCountersStat) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *IOCountersStat) GetReadCount() uint64 {
	if m != nil {
		return m.ReadCount
	}
	return 0
}

func (m *IOCountersStat) GetMergedReadCount() uint64 {
	if m != nil {
		return m.MergedReadCount
	}
	return 0
}

func (m *IOCountersStat) GetWriteCount() uint64 {
	if m != nil {
		return m.WriteCount
	}
	return 0
}

func (m *IOCountersStat) GetMergedWriteCount() uint64 {
	if m != nil {
		return m.MergedWriteCount
	}
	return 0
}

func (m *IOCountersStat) GetReadBytes() uint64 {
	if m != nil {
		return m.ReadBytes
	}
	return 0
}

func (m *IOCountersStat) GetWriteBytes() uint64 {
	if m != nil {
		return m.WriteBytes
	}
	return 0
}

func (m *IOCountersStat) GetReadTime() uint64 {
	if m != nil {
		return m.ReadTime
	}
	return 0
}

func (m *IOCountersStat) GetWriteTime() uint64 {
	if m != nil {
		return m.WriteTime
	}
	return 0
}

func (m *IOCountersStat) GetIopsInProgress() uint64 {
	if m != nil {
		return m.IopsInProgress
	}
	return 0
}

func (m *IOCountersStat) GetIoTime() uint64 {
	if m != nil {
		return m.IoTime
	}
	return 0
}

func (m *IOCountersStat) GetWeightedIO() uint64 {
	if m != nil {
		return m.WeightedIO
	}
	return 0
}

func (m *IOCountersStat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IOCountersStat) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *IOCountersStat) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type DiskRequest struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IP                   string               `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	NodeName             string               `protobuf:"bytes,3,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	UsageStat            []*UsageStat         `protobuf:"bytes,4,rep,name=usageStat,proto3" json:"usageStat,omitempty"`
	PartitionStat        []*PartitionStat     `protobuf:"bytes,5,rep,name=partitionStat,proto3" json:"partitionStat,omitempty"`
	IoCountersStat       []*IOCountersStat    `protobuf:"bytes,6,rep,name=ioCountersStat,proto3" json:"ioCountersStat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiskRequest) Reset()         { *m = DiskRequest{} }
func (m *DiskRequest) String() string { return proto.CompactTextString(m) }
func (*DiskRequest) ProtoMessage()    {}
func (*DiskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87be47849fd92a15, []int{3}
}

func (m *DiskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskRequest.Unmarshal(m, b)
}
func (m *DiskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskRequest.Marshal(b, m, deterministic)
}
func (m *DiskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskRequest.Merge(m, src)
}
func (m *DiskRequest) XXX_Size() int {
	return xxx_messageInfo_DiskRequest.Size(m)
}
func (m *DiskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskRequest proto.InternalMessageInfo

func (m *DiskRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DiskRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *DiskRequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *DiskRequest) GetUsageStat() []*UsageStat {
	if m != nil {
		return m.UsageStat
	}
	return nil
}

func (m *DiskRequest) GetPartitionStat() []*PartitionStat {
	if m != nil {
		return m.PartitionStat
	}
	return nil
}

func (m *DiskRequest) GetIoCountersStat() []*IOCountersStat {
	if m != nil {
		return m.IoCountersStat
	}
	return nil
}

type DiskResponse struct {
	Error                *basic.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DiskResponse) Reset()         { *m = DiskResponse{} }
func (m *DiskResponse) String() string { return proto.CompactTextString(m) }
func (*DiskResponse) ProtoMessage()    {}
func (*DiskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87be47849fd92a15, []int{4}
}

func (m *DiskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskResponse.Unmarshal(m, b)
}
func (m *DiskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskResponse.Marshal(b, m, deterministic)
}
func (m *DiskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskResponse.Merge(m, src)
}
func (m *DiskResponse) XXX_Size() int {
	return xxx_messageInfo_DiskResponse.Size(m)
}
func (m *DiskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiskResponse proto.InternalMessageInfo

func (m *DiskResponse) GetError() *basic.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*UsageStat)(nil), "protobuf.pb.disk.UsageStat")
	proto.RegisterType((*PartitionStat)(nil), "protobuf.pb.disk.PartitionStat")
	proto.RegisterType((*IOCountersStat)(nil), "protobuf.pb.disk.IOCountersStat")
	proto.RegisterType((*DiskRequest)(nil), "protobuf.pb.disk.DiskRequest")
	proto.RegisterType((*DiskResponse)(nil), "protobuf.pb.disk.DiskResponse")
}

func init() { proto.RegisterFile("disk/disk.proto", fileDescriptor_87be47849fd92a15) }

var fileDescriptor_87be47849fd92a15 = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6e, 0xda, 0x4c,
	0x10, 0xfe, 0x21, 0x86, 0x84, 0x21, 0x21, 0xc9, 0xea, 0xff, 0xa3, 0x15, 0x7f, 0x9b, 0x20, 0x0e,
	0x15, 0x6a, 0x8b, 0x91, 0xd2, 0x4b, 0xab, 0xde, 0xd2, 0xa4, 0x2a, 0x97, 0x04, 0x39, 0x89, 0x2a,
	0xf5, 0x66, 0xc3, 0x60, 0x56, 0xb1, 0xbd, 0xee, 0xee, 0xba, 0x51, 0xee, 0x7d, 0x80, 0xbe, 0x48,
	0x9f, 0xa1, 0xcf, 0xd2, 0x37, 0xa9, 0x76, 0xd7, 0xd8, 0x06, 0xd4, 0x13, 0x17, 0xd8, 0xf9, 0xe6,
	0x9b, 0x6f, 0x87, 0x99, 0xd9, 0x01, 0x0e, 0x67, 0x4c, 0x3e, 0x8c, 0xf4, 0x87, 0x9b, 0x0a, 0xae,
	0x38, 0x39, 0x32, 0x5f, 0x41, 0x36, 0x77, 0xd3, 0xc0, 0xd5, 0x78, 0xf7, 0x38, 0xf0, 0x25, 0x9b,
	0x8e, 0x50, 0x08, 0x2e, 0x2c, 0xa9, 0x7b, 0x16, 0x72, 0x1e, 0x46, 0x38, 0x5a, 0x72, 0x47, 0x8a,
	0xc5, 0x28, 0x95, 0x1f, 0xa7, 0x96, 0xd0, 0xff, 0x5d, 0x87, 0xd6, 0xbd, 0xf4, 0x43, 0xbc, 0x55,
	0xbe, 0x22, 0x6f, 0xa1, 0x55, 0x10, 0x68, 0xad, 0x57, 0x1b, 0xb4, 0xcf, 0xbb, 0xae, 0x95, 0x70,
	0x8b, 0xeb, 0xee, 0x96, 0x0c, 0xaf, 0x24, 0x13, 0x02, 0x4e, 0xea, 0xab, 0x05, 0xad, 0xf7, 0x6a,
	0x83, 0x96, 0x67, 0xce, 0xe4, 0x04, 0x9a, 0x73, 0xa9, 0x9e, 0x52, 0xa4, 0x3b, 0x06, 0xcd, 0x2d,
	0xf2, 0x2f, 0x34, 0x14, 0x57, 0x7e, 0x44, 0x9d, 0x5e, 0x6d, 0xe0, 0x78, 0xd6, 0xd0, 0x0a, 0x73,
	0x81, 0x48, 0x1b, 0x06, 0x34, 0x67, 0x8d, 0x65, 0x12, 0x67, 0xb4, 0x69, 0x31, 0x7d, 0x26, 0x3d,
	0x68, 0xeb, 0xef, 0x09, 0x8a, 0x29, 0x26, 0x8a, 0xee, 0xf6, 0x6a, 0x83, 0x9a, 0x57, 0x85, 0x34,
	0x83, 0x25, 0x7c, 0x86, 0xf2, 0xce, 0xdc, 0xb2, 0x67, 0x82, 0xab, 0x10, 0x39, 0x05, 0xb0, 0xe6,
	0xbd, 0x56, 0x6f, 0x19, 0x42, 0x05, 0x29, 0xfd, 0x1f, 0x75, 0x46, 0x50, 0xf5, 0x6b, 0x84, 0xbc,
	0x86, 0xe3, 0x92, 0xbd, 0xcc, 0xa4, 0x6d, 0x32, 0xd9, 0x74, 0xf4, 0x7f, 0xd6, 0xe0, 0x60, 0xe2,
	0x0b, 0xc5, 0x14, 0xe3, 0xc9, 0x96, 0x75, 0x3e, 0x81, 0xe6, 0x0c, 0xbf, 0xb1, 0x29, 0xe6, 0x95,
	0xce, 0x2d, 0x9d, 0x71, 0xcc, 0xb3, 0x44, 0xa5, 0x9c, 0x25, 0x2a, 0xaf, 0x77, 0x05, 0xa9, 0xf4,
	0xc2, 0x59, 0xe9, 0x05, 0x01, 0x87, 0xa7, 0x4a, 0x9a, 0xaa, 0xb7, 0x3c, 0x73, 0xee, 0x7f, 0x77,
	0xa0, 0x33, 0xbe, 0xf9, 0xa0, 0x83, 0x51, 0xc8, 0x2d, 0x13, 0x7e, 0x06, 0x2d, 0x81, 0xfe, 0xcc,
	0xa8, 0x99, 0x9c, 0x1d, 0xaf, 0x04, 0xc8, 0x00, 0x0e, 0x63, 0x14, 0x21, 0xce, 0xbc, 0x82, 0xb3,
	0x63, 0x38, 0xeb, 0xb0, 0xfe, 0x81, 0x8f, 0x82, 0x29, 0xb4, 0x24, 0x3b, 0x39, 0x15, 0x84, 0xbc,
	0x84, 0x23, 0x1b, 0xf2, 0xb9, 0x64, 0xd9, 0x51, 0xda, 0xc0, 0x97, 0x39, 0x5d, 0x3c, 0x29, 0x94,
	0xf9, 0x6c, 0x95, 0x40, 0x71, 0x93, 0x75, 0xef, 0x56, 0x6e, 0xb2, 0xfe, 0x2e, 0xec, 0x69, 0xb2,
	0xfe, 0xb5, 0xf9, 0x6c, 0x15, 0xb6, 0x56, 0x36, 0x4c, 0xe3, 0xb4, 0x73, 0x55, 0x02, 0xe4, 0x05,
	0x74, 0x18, 0x4f, 0xe5, 0x38, 0x99, 0x08, 0x1e, 0x0a, 0x94, 0x32, 0x1f, 0xad, 0x35, 0x54, 0x37,
	0x8b, 0x71, 0x23, 0xd1, 0x36, 0xfe, 0xdc, 0x32, 0x99, 0x21, 0x0b, 0x17, 0x0a, 0x67, 0xe3, 0x1b,
	0xba, 0x9f, 0x67, 0x56, 0x20, 0xba, 0x99, 0x89, 0x1f, 0x23, 0x3d, 0xb0, 0xcd, 0xd4, 0x67, 0xd2,
	0x87, 0x7d, 0x89, 0x82, 0xf9, 0xd1, 0x75, 0x16, 0x07, 0x28, 0x68, 0xc7, 0xf8, 0x56, 0x30, 0xfd,
	0x20, 0x23, 0x3f, 0xc0, 0x88, 0x1e, 0x1a, 0xa7, 0x35, 0xfa, 0xbf, 0xea, 0xd0, 0xbe, 0x64, 0xf2,
	0xc1, 0xc3, 0xaf, 0x19, 0xca, 0x6d, 0x66, 0xa0, 0x03, 0xf5, 0xf1, 0x24, 0x1f, 0xd8, 0xfa, 0x78,
	0xa2, 0x2b, 0xa8, 0x1f, 0xc9, 0xb5, 0xce, 0xd5, 0x8e, 0x6a, 0x61, 0x93, 0x77, 0xd0, 0xca, 0x96,
	0xfb, 0x88, 0x3a, 0xbd, 0x9d, 0x41, 0xfb, 0xfc, 0x7f, 0x77, 0x7d, 0xd5, 0xb9, 0xc5, 0xca, 0xf2,
	0x4a, 0x36, 0xb9, 0x82, 0x83, 0xb4, 0xfa, 0xcc, 0x68, 0xc3, 0x84, 0x9f, 0x6d, 0x86, 0xaf, 0xbc,
	0x46, 0x6f, 0x35, 0x8a, 0x7c, 0xd2, 0x5d, 0xaa, 0x4e, 0x3f, 0x6d, 0x1a, 0x9d, 0xde, 0xa6, 0xce,
	0xea, 0x2b, 0xf1, 0xd6, 0xe2, 0xfa, 0xef, 0x61, 0xdf, 0x16, 0x50, 0xa6, 0x3c, 0x91, 0x48, 0x5e,
	0x41, 0xc3, 0x2c, 0xe7, 0xbc, 0x7a, 0xff, 0x95, 0x82, 0x66, 0x73, 0xbb, 0x57, 0xda, 0xe9, 0x59,
	0xce, 0xf9, 0x8f, 0xbc, 0xfc, 0xb7, 0x28, 0xcc, 0x0b, 0xbf, 0x83, 0xe3, 0x49, 0x26, 0x17, 0x1a,
	0x2a, 0x17, 0xf6, 0xf3, 0xcd, 0x9c, 0x2a, 0x2d, 0xeb, 0x9e, 0xfe, 0xcd, 0x6d, 0x13, 0xea, 0xff,
	0xb3, 0x54, 0x5d, 0x5d, 0x4f, 0x5b, 0xab, 0xde, 0x03, 0xd1, 0xaa, 0x6b, 0x4b, 0x64, 0x5b, 0xd9,
	0x8b, 0xcb, 0x2f, 0x17, 0x21, 0x53, 0x8b, 0x2c, 0x70, 0xa7, 0x3c, 0x1e, 0xc5, 0x6c, 0x2a, 0xf8,
	0x90, 0x25, 0xc3, 0x69, 0x32, 0x4a, 0x23, 0x5f, 0xcd, 0xb9, 0x88, 0x87, 0x8f, 0x18, 0x8c, 0x7c,
	0x29, 0x31, 0x0e, 0xa2, 0xa7, 0x61, 0xc4, 0x92, 0xca, 0x5f, 0x5f, 0xc8, 0xcd, 0xdf, 0x67, 0xd0,
	0x34, 0xc8, 0x9b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x31, 0x68, 0x2e, 0x52, 0x07, 0x00,
	0x00,
}
