// Code generated by protoc-gen-go. DO NOT EDIT.
// source: host/host.proto

package host

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	basic "github.com/micro-in-cn/platform-web/assembly-line/protobuf/go/basic"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HostInfo struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hostname             string               `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Uptime               uint64               `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	BootTime             uint64               `protobuf:"varint,4,opt,name=bootTime,proto3" json:"bootTime,omitempty"`
	Procs                uint64               `protobuf:"varint,5,opt,name=procs,proto3" json:"procs,omitempty"`
	OS                   string               `protobuf:"bytes,6,opt,name=oS,proto3" json:"oS,omitempty"`
	Platform             string               `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformFamily       string               `protobuf:"bytes,8,opt,name=platformFamily,proto3" json:"platformFamily,omitempty"`
	PlatformVersion      string               `protobuf:"bytes,9,opt,name=platformVersion,proto3" json:"platformVersion,omitempty"`
	KernelVersion        string               `protobuf:"bytes,10,opt,name=kernelVersion,proto3" json:"kernelVersion,omitempty"`
	VirtualizationSystem string               `protobuf:"bytes,11,opt,name=virtualizationSystem,proto3" json:"virtualizationSystem,omitempty"`
	VirtualizationRole   string               `protobuf:"bytes,12,opt,name=virtualizationRole,proto3" json:"virtualizationRole,omitempty"`
	HostID               string               `protobuf:"bytes,13,opt,name=hostID,proto3" json:"hostID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HostInfo) Reset()         { *m = HostInfo{} }
func (m *HostInfo) String() string { return proto.CompactTextString(m) }
func (*HostInfo) ProtoMessage()    {}
func (*HostInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ae3045e493c4c4f, []int{0}
}

func (m *HostInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfo.Unmarshal(m, b)
}
func (m *HostInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfo.Marshal(b, m, deterministic)
}
func (m *HostInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfo.Merge(m, src)
}
func (m *HostInfo) XXX_Size() int {
	return xxx_messageInfo_HostInfo.Size(m)
}
func (m *HostInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfo proto.InternalMessageInfo

func (m *HostInfo) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *HostInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *HostInfo) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *HostInfo) GetBootTime() uint64 {
	if m != nil {
		return m.BootTime
	}
	return 0
}

func (m *HostInfo) GetProcs() uint64 {
	if m != nil {
		return m.Procs
	}
	return 0
}

func (m *HostInfo) GetOS() string {
	if m != nil {
		return m.OS
	}
	return ""
}

func (m *HostInfo) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *HostInfo) GetPlatformFamily() string {
	if m != nil {
		return m.PlatformFamily
	}
	return ""
}

func (m *HostInfo) GetPlatformVersion() string {
	if m != nil {
		return m.PlatformVersion
	}
	return ""
}

func (m *HostInfo) GetKernelVersion() string {
	if m != nil {
		return m.KernelVersion
	}
	return ""
}

func (m *HostInfo) GetVirtualizationSystem() string {
	if m != nil {
		return m.VirtualizationSystem
	}
	return ""
}

func (m *HostInfo) GetVirtualizationRole() string {
	if m != nil {
		return m.VirtualizationRole
	}
	return ""
}

func (m *HostInfo) GetHostID() string {
	if m != nil {
		return m.HostID
	}
	return ""
}

type HostRequest struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IP                   string               `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	NodeName             string               `protobuf:"bytes,3,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	HostInfo             []*HostInfo          `protobuf:"bytes,4,rep,name=hostInfo,proto3" json:"hostInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HostRequest) Reset()         { *m = HostRequest{} }
func (m *HostRequest) String() string { return proto.CompactTextString(m) }
func (*HostRequest) ProtoMessage()    {}
func (*HostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ae3045e493c4c4f, []int{1}
}

func (m *HostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostRequest.Unmarshal(m, b)
}
func (m *HostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostRequest.Marshal(b, m, deterministic)
}
func (m *HostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostRequest.Merge(m, src)
}
func (m *HostRequest) XXX_Size() int {
	return xxx_messageInfo_HostRequest.Size(m)
}
func (m *HostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostRequest proto.InternalMessageInfo

func (m *HostRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *HostRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *HostRequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *HostRequest) GetHostInfo() []*HostInfo {
	if m != nil {
		return m.HostInfo
	}
	return nil
}

type HostResponse struct {
	Error                *basic.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HostResponse) Reset()         { *m = HostResponse{} }
func (m *HostResponse) String() string { return proto.CompactTextString(m) }
func (*HostResponse) ProtoMessage()    {}
func (*HostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ae3045e493c4c4f, []int{2}
}

func (m *HostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostResponse.Unmarshal(m, b)
}
func (m *HostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostResponse.Marshal(b, m, deterministic)
}
func (m *HostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostResponse.Merge(m, src)
}
func (m *HostResponse) XXX_Size() int {
	return xxx_messageInfo_HostResponse.Size(m)
}
func (m *HostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostResponse proto.InternalMessageInfo

func (m *HostResponse) GetError() *basic.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*HostInfo)(nil), "protobuf.pb.host.HostInfo")
	proto.RegisterType((*HostRequest)(nil), "protobuf.pb.host.HostRequest")
	proto.RegisterType((*HostResponse)(nil), "protobuf.pb.host.HostResponse")
}

func init() { proto.RegisterFile("host/host.proto", fileDescriptor_6ae3045e493c4c4f) }

var fileDescriptor_6ae3045e493c4c4f = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x4d, 0xfa, 0xc3, 0x76, 0xda, 0xeb, 0xe9, 0x72, 0xca, 0x12, 0x50, 0x4b, 0x11, 0x29,
	0x48, 0x13, 0xa8, 0x20, 0x82, 0x6f, 0xc7, 0x29, 0xf6, 0x45, 0x4b, 0x2a, 0x3e, 0xf8, 0x20, 0x24,
	0x71, 0xdb, 0x2e, 0x26, 0x3b, 0x71, 0x77, 0x73, 0x52, 0xff, 0x25, 0xff, 0x13, 0xff, 0x2a, 0xd9,
	0xdd, 0x24, 0xe7, 0x95, 0xfa, 0xe4, 0x4b, 0xdb, 0x99, 0xef, 0x67, 0x67, 0xa7, 0x33, 0xdf, 0x85,
	0xf3, 0x3d, 0x2a, 0x1d, 0x99, 0x8f, 0xb0, 0x94, 0xa8, 0x91, 0xdc, 0xb3, 0x5f, 0x69, 0xb5, 0x0d,
	0xcb, 0x34, 0x34, 0xf9, 0xe0, 0x7e, 0x9a, 0x28, 0x9e, 0x45, 0x4c, 0x4a, 0x94, 0x0e, 0x0a, 0x9e,
	0xec, 0x10, 0x77, 0x39, 0x8b, 0x1a, 0x36, 0xd2, 0xbc, 0x60, 0x4a, 0x27, 0x45, 0xe9, 0x80, 0xd9,
	0xef, 0x0e, 0x0c, 0xde, 0xa1, 0xd2, 0x2b, 0xb1, 0x45, 0xf2, 0x0a, 0x86, 0xad, 0x4e, 0xbd, 0xa9,
	0x37, 0x1f, 0x2d, 0x83, 0xd0, 0x55, 0x08, 0xdb, 0xdb, 0x3e, 0x36, 0x44, 0x7c, 0x03, 0x93, 0x00,
	0x06, 0xa6, 0x05, 0x91, 0x14, 0x8c, 0xfa, 0x53, 0x6f, 0x3e, 0x8c, 0xdb, 0x98, 0x3c, 0x84, 0x7e,
	0x55, 0x1a, 0x94, 0x76, 0xa6, 0xde, 0xbc, 0x1b, 0xd7, 0x91, 0x39, 0x93, 0x22, 0x6a, 0x53, 0x8f,
	0x76, 0xad, 0xd2, 0xc6, 0xe4, 0x02, 0x7a, 0xa5, 0xc4, 0x4c, 0xd1, 0x9e, 0x15, 0x5c, 0x40, 0x26,
	0xe0, 0xe3, 0x86, 0xf6, 0x6d, 0x7d, 0x1f, 0x37, 0xa6, 0x42, 0x99, 0x27, 0x7a, 0x8b, 0xb2, 0xa0,
	0x77, 0xdd, 0xad, 0x4d, 0x4c, 0x9e, 0xc1, 0xa4, 0xf9, 0xfd, 0x36, 0x29, 0x78, 0x7e, 0xa0, 0x03,
	0x4b, 0x1c, 0x65, 0xc9, 0x1c, 0xce, 0x9b, 0xcc, 0x27, 0x26, 0x15, 0x47, 0x41, 0x87, 0x16, 0x3c,
	0x4e, 0x93, 0xa7, 0x70, 0xf6, 0x8d, 0x49, 0xc1, 0xf2, 0x86, 0x03, 0xcb, 0xdd, 0x4e, 0x92, 0x25,
	0x5c, 0x5c, 0x73, 0xa9, 0xab, 0x24, 0xe7, 0x3f, 0x13, 0xcd, 0x51, 0x6c, 0x0e, 0x4a, 0xb3, 0x82,
	0x8e, 0x2c, 0x7c, 0x52, 0x23, 0x21, 0x90, 0xdb, 0xf9, 0x18, 0x73, 0x46, 0xc7, 0xf6, 0xc4, 0x09,
	0xc5, 0x4c, 0xd4, 0x4c, 0x77, 0x75, 0x45, 0xcf, 0x2c, 0x53, 0x47, 0xb3, 0x5f, 0x1e, 0x8c, 0xcc,
	0x32, 0x63, 0xf6, 0xbd, 0x62, 0x4a, 0xff, 0xc7, 0x3e, 0x27, 0xe0, 0xaf, 0xd6, 0xf5, 0x26, 0xfd,
	0xd5, 0xda, 0x4c, 0x5a, 0xe0, 0x57, 0xf6, 0x3e, 0xa9, 0xb7, 0x38, 0x8c, 0xdb, 0x98, 0xbc, 0x74,
	0xbb, 0x37, 0x0e, 0xa2, 0xdd, 0x69, 0xc7, 0x5e, 0x72, 0xec, 0xcd, 0xb0, 0xf1, 0x58, 0xdc, 0xb2,
	0xb3, 0xd7, 0x30, 0x76, 0xcd, 0xaa, 0x12, 0x85, 0x62, 0xe4, 0x39, 0xf4, 0xac, 0x75, 0xeb, 0x4e,
	0x1f, 0xdc, 0x14, 0xb1, 0xbe, 0x0e, 0xdf, 0x18, 0x31, 0x76, 0xcc, 0xf2, 0x8b, 0xfb, 0xa7, 0x1b,
	0x26, 0xaf, 0x79, 0xc6, 0xc8, 0x07, 0x18, 0xaf, 0x2b, 0xb5, 0x6f, 0x9d, 0xfc, 0xe8, 0x74, 0x07,
	0xf5, 0x60, 0x82, 0xc7, 0xff, 0x92, 0x5d, 0x2b, 0xb3, 0x3b, 0x97, 0x57, 0x9f, 0x2f, 0x77, 0x5c,
	0xef, 0xab, 0x34, 0xcc, 0xb0, 0x88, 0x0a, 0x9e, 0x49, 0x5c, 0x70, 0xb1, 0xc8, 0x44, 0xd4, 0xd8,
	0x62, 0xf1, 0x83, 0xa5, 0x51, 0xa2, 0x14, 0x2b, 0xd2, 0xfc, 0xb0, 0xc8, 0xb9, 0xf8, 0xeb, 0x95,
	0xed, 0xd0, 0xbe, 0xd4, 0xb4, 0x6f, 0x33, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x83, 0x17,
	0x8b, 0x58, 0xbd, 0x03, 0x00, 0x00,
}
